trigger:
  branches:
    include:
      - develop
      - master

pr:
  branches:
    include:
      - develop
      - master

variables:
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: projectPath
    value: './CqrsApi.Core/CqrsApi.Core.csproj'

stages:
  - stage: 'Build_Test'
    jobs:
      - job: "Build"
        displayName: 'Build Test & Drop artifacts'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: templates/dotnet-build-steps-template.yml
            parameters:
              buildConfiguration: $(buildConfiguration)
              buildPlatform: $(buildPlatform)
              projectPath: $(projectPath)