trigger:
  branches:
    include:
      - develop
      - master

pr:
  branches:
    include:
      - develop
      - master

variables:
  - name: buildPlatform
    value: 'Any CPU'
  - name: buildConfiguration
    value: 'Release'
  - name: projectPath
    value: './CqrsApi.Core/CqrsApi.Core.csproj'
  - name: IISSiteName
    value: 'moviesapi'
  - name: IISPhysicalPath
    value: '%SystemDrive%\inetpub\wwwroot\$(IISSiteName)'

stages:
  - stage: 'Build_Test'
    jobs:
      - job: "Build"
        displayName: 'Build Test & Drop artifacts'
        pool:
          vmImage: 'ubuntu-latest'

        steps:
          - template: templates/dotnet-build-steps-template.yml
            parameters:
              buildConfiguration: $(buildConfiguration)
              buildPlatform: $(buildPlatform)
              projectPath: $(projectPath)

  - stage: 'dev'
    displayName: 'Deploy Movies dev'
    dependsOn: Build_Test
    condition: succeeded('Build_Test')
    jobs:
      - deployment: Deploy_Movies_Dev
        displayName: 'Deploy Movies dev'
        environment:
          name: dev
          resourceType: VirtualMachine
        strategy:
          runOnce:
            deploy:
              steps:
                - download: current
                  artifact: drop

                - task: IISWebAppManagementOnMachineGroup@0
                  inputs:
                    EnableIIS: true
                    IISDeploymentType: 'IISWebsite'
                    ActionIISWebsite: 'CreateOrUpdateWebsite'
                    WebsiteName: '$(IISSiteName)-$(Environment.Name)'
                    WebsitePhysicalPath: '$(IISSitePhysicalPath)'
                    AddBinding: true
                    Bindings: |
                      {
                          bindings: [
                            {
                              "protocol":"http",
                              "ipAddress":"*",
                              "hostname":"",
                              "port":"80",
                              "sslThumbprint":"",
                              "sniFlag":false
                            }
                          ]
                      }
                    CreateOrUpdateAppPoolForWebsite: true
                    ConfigureAuthenticationForWebsite: true
                    AppPoolNameForWebsite: '$(IISSiteName)-$(Environment.Name)'
                    DotNetVersionForWebsite: 'No Managed Code'
                    PipeLineModeForWebsite: 'Integrated'
                    AppPoolIdentityForWebsite: 'ApplicationPoolIdentity'
                    AnonymousAuthenticationForWebsite: true
                    BasicAuthenticationForWebsite: false
                    WindowsAuthenticationForWebsite: false

                - task: IISWebAppDeploymentOnMachineGroup@0
                  displayName: 'IIS Web App Deploy'
                  inputs:
                    WebSiteName: '$(IISSiteName)-$(Environment.Name)'
                    TakeAppOfflineFlag: true
                    Package: '$(Pipeline.Workspace)/drop/$(BuildConfiguration)/CqrsApi.Core.zip'
                    JSONFiles: '**/appsettings.json'